import React from "react"; // KHông có cái này thì framework React của JS sẽ kh sử dụng được
import { Sheet, Button, Page, Text, useNavigate } from "zmp-ui"; 
//cái sheet,button ,page,text ,use Navigate thì cũng là component,asset thoit6

const AboutPage = (props) => { //Kỹ thuật ép hàm WHY? để mở dấu {} và viết JS bên trong
  //props là đối số truyền từ component bên ngoài
  //KHẢ NĂNG PROPS SAI
  const [actionSheetOpened, setActionSheetOpened] = React.useState(false);



//BẮT ĐẦU VỚI THANH ĐIỀU HƯỚNG
  const navigate = useNavigate() //Hỏi hàm đâu mà return thì useNavigate đó
  return (
    //<Page> ; <text></text> không là html và coi nó như component vì mục dịch reat là để hợp 2 thằng 

    //tụi nó cũng là core component của React framework được lấy ra từ  import React from "react"
    <Page className="page" style={{ paddingTop: '70px' }}> 
      <div className="section-container" >
        <Text>This mini app was generated by tech4gri</Text>
      </div>
      <div>
      <Button
        variant='secondary'
        fullWidth
        onClick={() => setActionSheetOpened(true)}
      >
        Back
      </Button>
      </div>
      <Sheet.Actions
        visible={actionSheetOpened}
        onClose={() => setActionSheetOpened(false)}
        actions={[
          [
            {
              text: "Go back",
              onClick: () => {
                navigate(-1);
              },
            },
            {
              text: "Action 1",
              close: true,
            },
            {
              text: "Action 2",
              close: true,
            },
          ],
          [
            {
              text: "Close",
              close: true,
              danger: true,
            },
          ],
        ]}
      ></Sheet.Actions>
    </Page>
    
  );
};

export default AboutPage;